// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHkQXG5nsvE3iyJiKFR3AF11GXECHbvU',
    appId: '1:879468964439:android:fba51605a60f5e6b065112',
    messagingSenderId: '879468964439',
    projectId: 'riverwatch-be1e4',
    databaseURL: 'https://riverwatch-be1e4.firebaseio.com',
    storageBucket: 'riverwatch-be1e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgXmpJY2s1LQ2gwTdRb6BaY2Zu0ToxwY',
    appId: '1:879468964439:ios:0dfd7ecd7def3870065112',
    messagingSenderId: '879468964439',
    projectId: 'riverwatch-be1e4',
    databaseURL: 'https://riverwatch-be1e4.firebaseio.com',
    storageBucket: 'riverwatch-be1e4.appspot.com',
    iosClientId: '879468964439-9p351s68de2l9r3mjlugamp92p4irf9h.apps.googleusercontent.com',
    iosBundleId: 'com.aquawatchsolutions.swimos',
  );
}
